services:
  termix:
    image: ghcr.io/lukegus/termix:latest #release-1.10.0
    container_name: middleware_termix
    restart: unless-stopped
    ports:
      - "8079:8080"
    volumes:
      - /docker/configs/termix:/app/data
    environment:
      PORT: "8080"