services:
  crosswatch:
    image: ghcr.io/cenodude/crosswatch:0.6.0
    container_name: media_servers_crosswatch
    ports:
      - "8787:8787"          # host:container
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /docker/configs/crosswatch:/config
    #network_mode: host
    restart: unless-stopped
