services:
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.0.0
    #init: true
    container_name: servarr_seerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Zurich
      - PORT=5054 #optional
    #user: root
    ports:
      - 5054:5054
    volumes:
      - /docker/configs/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5054/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped