services:
  dozzle-agent:
    image: amir20/dozzle:v10.0.2
    container_name: nextcloud_dozzle_agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    restart: unless-stopped
    environment:
    - DOZZLE_HOSTNAME=nextcloud
    network_mode: bridge
