services:
    agent:
        image: 'portainer/agent:2.38.1'
        volumes:
            - '/:/host'
            - '/var/lib/docker/volumes:/var/lib/docker/volumes'
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: unless-stopped
        container_name: media_servers_portainer_agent
        ports:
            - '9001:9001'
        network_mode: bridge
