services:
  castopod:
    image: castopod/castopod:1.14.0
    container_name: "media_servers_castopod"
    volumes:
      - /docker/configs/castopod/media:/var/www/castopod/public/media
    environment:
      MYSQL_DATABASE: castopod
      MYSQL_USER: castopod
      MYSQL_PASSWORD: ${CASTOPOD_PASSWORD}
      CP_BASEURL: ${CP_BASEURL}
      CP_ANALYTICS_SALT: ${CASTOPOD_PASSWORD}
      CP_CACHE_HANDLER: redis
      CP_REDIS_HOST: redis
      CP_REDIS_PASSWORD: ${CASTOPOD_PASSWORD}
    networks:
      - castopod
      - castopod-db
    ports:
      - 127.0.0.1:9000:8000
    restart: unless-stopped

  web:
    image: castopod/web-server:1.14.0
    container_name: media_servers_castopod_web
    depends_on:
      - castopod
    volumes:
      - /docker/configs/castopod/media:/var/www/html/media:ro
      - /docker/configs/castopod/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - castopod
    ports:
      - 8000:80
    restart: unless-stopped

  mariadb:
    image: mariadb:11.2
    container_name: "media_servers_castopod_db"
    networks:
      - castopod-db
    volumes:
      - /docker/configs/castopod/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${CASTOPOD_PASSWORD}
      MYSQL_DATABASE: castopod
      MYSQL_USER: castopod
      MYSQL_PASSWORD: ${CASTOPOD_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: "media_servers_castopod_redis"
    command: --requirepass ${CASTOPOD_PASSWORD}
    volumes:
      - /docker/configs/castopod/cache:/data
    networks:
      - castopod
    restart: unless-stopped

networks:
  castopod:
  castopod-db: