services:
  github-runner:
    image: myoung34/github-runner:2.331.0
    container_name: tools_github_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/configs/github_runner/work:/tmp/runner
      - /docker/configs/github_runner/config:/etc/runner
    environment:
      ORG_NAME: nikolanovoselec
      ACCESS_TOKEN: ${GH_RUNNER_ACCESS_TOKEN}
      RUNNER_NAME: komodo-runner
      RUNNER_WORKDIR: /tmp/runner
      LABELS: self-hosted,linux,docker
      DISABLE_AUTO_UPDATE: 'true'
    restart: unless-stopped
    network_mode: bridge
