services:
  github-runner:
    image: myoung34/github-runner:ubuntu-jammy
    container_name: tools_github_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/configs/github_runner/work:/tmp/runner
      - /docker/configs/github_runner/config:/etc/runner
    environment:
      REPO_URL: https://github.com/nikolanovoselec/claudeflare
      ACCESS_TOKEN: ${GH_RUNNER_ACCESS_TOKEN}
      RUNNER_NAME: komodo-runner
      RUNNER_WORKDIR: /tmp/runner
      LABELS: tools_github_runner
      DISABLE_AUTO_UPDATE: 'true'
    restart: unless-stopped
    network_mode: bridge
