services:

  github-runner-codeflare:
    image: myoung34/github-runner:2.331.0-ubuntu-jammy
    container_name: tools_github_runner_codeflare
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/configs/github_runner/codeflare/work:/tmp/runner
      - /docker/configs/github_runner/codeflare/config:/etc/runner
    environment:
      REPO_URL: https://github.com/nikolanovoselec/codeflare
      ACCESS_TOKEN: ${GH_RUNNER_ACCESS_TOKEN}
      RUNNER_NAME: tools_github_runner
      RUNNER_WORKDIR: /tmp/runner
      LABELS: tools_github_runner
      DISABLE_AUTO_UPDATE: 'true'
    restart: unless-stopped
    network_mode: bridge