services:
    agent:
        image: 'portainer/agent:2.37.0'
        volumes:
            - '/:/host'
            - '/volume1/@docker/:/var/lib/docker/volumes'
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: unless-stopped
        container_name: storage_portainer_agent
        ports:
            - '9001:9001'
        network_mode: bridge
